### ISSUE TITLE
Transition to kw-only arguments

### ISSUE THREAD

**Issue by hmaarrfk** [hmaarrfk/wabisabi#3]
Hey @jni, I feel like a fun (and useful) one to write would be something transitioning to keyword only arguments.

I know you had mentioned that you wanted to make some function kw-only in scikit-image. I really think that this kind of decorator is the way to go if you want to keep your code legible.

**Comment by hmaarrfk** [comment]
Mostly I want you thoughts on this, to see if it is even useful.

I thought about inclding this straight into scikit-image, but I felt like a 100+ line function for a decorator was probably outside the scope of scikit-image, and likely more generally applicable.

**Comment by jni** [comment]
@hmaarrfk I was thinking of something more drastic for skimage: At 0.15, we warn in the release notes that we are going kw-only in 1.0. When we go 1.0, we just pull the trigger. With sufficient documentation (FAQs about how to fix things, two releases of warnings), I think this is cleaner. Adding a decorator to *every* function doesn't sound clean to me.

Apart from that, it might be fun, but not for me. =P

**Comment by hmaarrfk** [comment]
You will break everybody’s code.

Don’t do that!!!

It is impossible to find those hidden calls to sculpt image functions you
have hidden somewhere without the library telling you.

**Comment by jni** [comment]
@hmaarrfk Don't get all panicky, no decisions have been made yet, let alone taken. =) Several points:

- breaking code is acceptable *if* you can very clearly guide the fix *and* the fix is "nice". See e.g. returning tuple from `regular_grid`. We will break code *eventually* so the question is when the pain should happen and for how long.
- A 1.0 release is *arguably* the best place to do this.
- Adding a keyword-only deprecation decorator to Every. Single. Function. is a *lot* of churn for limited benefit.

Discussions with @JDWarner have swayed me somewhat with regards to when things should break and how to handle deprecations. I was definitely in favour of "never break the API except over several releases" before, but now I think that in many cases this just postpones the pain, rather than avoid it.

In this case, libraries that have long calls with many unnamed positional arguments will get TypeErrors from the precise location of those calls. If they can find how to fix those TypeErrors easily, then it's not a huge deal.

The one thing that makes me undecided here is that the only way to *actually* tell people what's going on, without them having to Google to get our release notes/FAQ, is to use a decorator on every function. At that point I might favour deprecation again. :joy: If we go the deprecation route, though, I would want it to happen in 0.15, so that by 1.0 we have keyword-only arguments everywhere that they make sense.

**Comment by hmaarrfk** [comment]
For me, keyword arguments are "nice-to-haves" and not "must-haves". 

No point in breaking working code just to enforce an easier learning curve.

I think the beauty of python is that you don't need to ever go google for something 😸 you can type
```
help(function)
```

**Comment by jni** [comment]
@hmaarrfk The big benefit of kwarg-only kwargs is in future deprecations. Changing argument names becomes much much easier in the future if they are keyword-only arguments.

Also, if users get a `TypeError` from a skimage function from a keyword-only argument, then `help(function)` will tell them the solution.

**Comment by jni** [comment]
I'll mention another benefit actually, which is correctness. I had a major error in one of my papers because I changed an API by deleting an argument but didn't change a corresponding call elsewhere in the code. This caused a frameshift mutation in the arguments. This would not have happened had my arguments been keyword-only.

**Comment by hmaarrfk** [comment]
I agree that keyword arguments make your code more robust. I guess
philosophically, I'm OK with others shooting themselves in the foot.

**Comment by jni** [comment]
> I guess philosophically, I'm OK with others shooting themselves in the foot.

Great! I await your PR ripping out all input validation from skimage. =P

**Comment by hmaarrfk** [comment]
You've already heard me kick and scream about validating that things are between 0 and 1 :cat:

**Comment by JDWarner** [comment]
In seriousness, personally I'd be fine removing at least some input checks - if the resultant errors are comprehensible.  That's not the general case, but try ripping them out piecemeal and seeing how the traceback looks from the standpoint of a user; this is my personal litmus test for when to catch or add checks.

**Comment by hmaarrfk** [comment]
One challenge I see, is that we often become experts and forget how intimidating a traceback looks. No matter how well formatted it is...
